<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQ5QNiWu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQ5QNiWu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQ5QNiWu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQ5QNiWu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQ5QNiWu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Q5QNiWu',
    'container.build_id' => 'b02b8c7f',
    'container.build_time' => 1684762857,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQ5QNiWu');
