<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_upload_form' => [[], ['_controller' => 'App\\Controller\\ApiMemberController::userSetForm'], [], [['text', '/api/v1/user/add-file']], [], [], []],
    'api_change_password' => [[], ['_controller' => 'App\\Controller\\ApiMemberController::changePassword'], [], [['text', '/api/v1/user/change-password']], [], [], []],
    'api_auth_token' => [[], ['_controller' => 'App\\Controller\\ApiMemberController::authToken'], [], [['text', '/api/v1/user/auth-token']], [], [], []],
    'web_member' => [[], ['_controller' => 'App\\Controller\\MemberController::userCreate'], [], [['text', '/web/register']], [], [], []],
    'web_auth' => [[], ['_controller' => 'App\\Controller\\MemberController::web_auth'], [], [['text', '/web/auth']], [], [], []],
    'web_login' => [[], ['_controller' => 'App\\Controller\\MemberController::login'], [], [['text', '/web/login']], [], [], []],
    'web_change_password' => [[], ['_controller' => 'App\\Controller\\MemberController::changePassword'], [], [['text', '/web/change-password']], [], [], []],
    'web_app_member_edit' => [[], ['_controller' => 'App\\Controller\\MemberController::edit'], [], [['text', '/web/edit']], [], [], []],
    'web_app_member_removemarketplacedata' => [[], ['_controller' => 'App\\Controller\\MemberController::removeMarketPlaceData'], [], [['text', '/web/remove']], [], [], []],
    'result_list' => [['page'], ['page' => 1, '_controller' => 'App\\Controller\\IndexController::index'], ['page' => '\\d+'], [['variable', '/', '\\d+', 'page', true], ['text', '/web/admin/listing']], [], [], []],
    'result_list_query' => [['q', 'page'], ['page' => 1, '_controller' => 'App\\Controller\\MemberController::index'], ['page' => '\\d+'], [['variable', '/', '\\d+', 'page', true], ['variable', '/', '[^/]++', 'q', true], ['text', '/web/admin/listing']], [], [], []],
    'result_edit_query' => [['page'], ['page' => 1, '_controller' => 'App\\Controller\\MemberController::edit'], ['page' => '\\d+'], [['variable', '/', '\\d+', 'page', true], ['text', '/web/edit']], [], [], []],
    'result_search_filter' => [[], ['_controller' => 'App\\Controller\\IndexController::getSearchFilter'], [], [['text', '/web/search-filter']], [], [], []],
];
