<?php

namespace ContainerQ5QNiWu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CmwTO6OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cmwTO6O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cmwTO6O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'pager' => ['privates', 'App\\Configs\\Pager', 'getPagerService', true],
        ], [
            'pager' => 'App\\Configs\\Pager',
        ]);
    }
}
