<?php

namespace ContainerQ5QNiWu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OWippmOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OWippmO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OWippmO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'fileUploader' => ['privates', 'App\\Service\\FileUploader', 'getFileUploaderService', true],
            'filesPath' => [(\dirname(__DIR__, 4).'/public/files/')],
        ], [
            'fileUploader' => 'App\\Service\\FileUploader',
            'filesPath' => '?',
        ]);
    }
}
