<?php

namespace ContainerQ5QNiWu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FuvgG8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fuvgG_8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fuvgG_8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ApiMemberController::change_password' => ['privates', '.service_locator.tp5ABh6', 'get_ServiceLocator_Tp5ABh6Service', true],
            'App\\Controller\\ApiMemberController::jsonAddFile' => ['privates', '.service_locator.EmunBvm', 'get_ServiceLocator_EmunBvmService', true],
            'App\\Controller\\ApiMemberController::userSetForm' => ['privates', '.service_locator.OWippmO', 'get_ServiceLocator_OWippmOService', true],
            'App\\Controller\\IndexController::index' => ['privates', '.service_locator.cmwTO6O', 'get_ServiceLocator_CmwTO6OService', true],
            'App\\Controller\\MemberController::changePassword' => ['privates', '.service_locator.tp5ABh6', 'get_ServiceLocator_Tp5ABh6Service', true],
            'App\\Controller\\MemberController::userCreate' => ['privates', '.service_locator.9ntDYZj', 'get_ServiceLocator_9ntDYZjService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ApiMemberController:change_password' => ['privates', '.service_locator.tp5ABh6', 'get_ServiceLocator_Tp5ABh6Service', true],
            'App\\Controller\\ApiMemberController:jsonAddFile' => ['privates', '.service_locator.EmunBvm', 'get_ServiceLocator_EmunBvmService', true],
            'App\\Controller\\ApiMemberController:userSetForm' => ['privates', '.service_locator.OWippmO', 'get_ServiceLocator_OWippmOService', true],
            'App\\Controller\\IndexController:index' => ['privates', '.service_locator.cmwTO6O', 'get_ServiceLocator_CmwTO6OService', true],
            'App\\Controller\\MemberController:changePassword' => ['privates', '.service_locator.tp5ABh6', 'get_ServiceLocator_Tp5ABh6Service', true],
            'App\\Controller\\MemberController:userCreate' => ['privates', '.service_locator.9ntDYZj', 'get_ServiceLocator_9ntDYZjService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ApiMemberController::change_password' => '?',
            'App\\Controller\\ApiMemberController::jsonAddFile' => '?',
            'App\\Controller\\ApiMemberController::userSetForm' => '?',
            'App\\Controller\\IndexController::index' => '?',
            'App\\Controller\\MemberController::changePassword' => '?',
            'App\\Controller\\MemberController::userCreate' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ApiMemberController:change_password' => '?',
            'App\\Controller\\ApiMemberController:jsonAddFile' => '?',
            'App\\Controller\\ApiMemberController:userSetForm' => '?',
            'App\\Controller\\IndexController:index' => '?',
            'App\\Controller\\MemberController:changePassword' => '?',
            'App\\Controller\\MemberController:userCreate' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
