<?php

namespace ContainerQ5QNiWu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPagerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Configs\Pager' shared autowired service.
     *
     * @return \App\Configs\Pager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Configs'.\DIRECTORY_SEPARATOR.'Pager.php';

        return $container->privates['App\\Configs\\Pager'] = new \App\Configs\Pager();
    }
}
